map_type:             costmap
#obstacle_range:       3.0
#raytrace_range:       3.0
transform_tolerance:  2.0
footprint: [[0.22, 0.22], [0.22, -0.22], [-0.40, -0.22], [-0.40, 0.22]]
#robot_radius:        0.0 
