global_costmap:
   global_frame: map
   robot_base_frame: base_link
   update_frequency: 1.0
   publish_frequency: 0.5
   width: 50.0
   height: 50.0
   resolution: 0.02
   static_map: true
   rolling_window: false       
 
   plugins:
    - {name: static_layer, type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer, type: "costmap_2d::ObstacleLayer"}
    - {name: inflated_layer, type: "costmap_2d::InflationLayer"}

   obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, 
    data_type: LaserScan, 
    topic: scan, marking: false, 
    clearing: true, 
    max_obstacle_height: 3, 
    min_obstacle_height: 0, 
    inf_is_valid: true, 
    obstacle_range: 5.0, 
    combination_method: 0,
    raytrace_range: 5.0}

   inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 0.3
#global_costmap:
   #global_frame:      map
   #robot_base_frame:  robot_footprint
   #update_frequency:  15.0 #10.0
   #publish_frequency: 15.0 #10.0
   #width:             20.0 #50.0
   #height:            20.0 #50.0
   #resolution:        0.05 #0.02
   #static_map:        true
   #rolling_window:    false
