local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 1.0
  publish_frequency: 5.0
  static_map: false
  rolling_window: true
  width: 7.0
  height: 7.0
  resolution: 0.05

  plugins:
            -  {name: obstacle_layer, type: "costmap_2d::ObstacleLayer", output: "screen"}
            -  {name: inflation_layer, type: "costmap_2d::InflationLayer", output: "screen"}

  obstacle_layer:
    observation_sources: laser_scan_sensor
    laser_scan_sensor: {sensor_frame: laser_frame, 
    data_type: LaserScan, 
    topic: scan, marking: true, 
    clearing: true, 
    max_obstacle_height: 3, 
    min_obstacle_height: 0, 
    inf_is_valid: true, 
    obstacle_range: 7.0, 
    combination_method: 0,
    raytrace_range: 7.0}

  inflation_layer:
        cost_scaling_factor: 10.0
        inflation_radius: 1.0
