rosplan_demo_waypoints:
    # waypoints reference frame
    waypoint_frameid: map

    # waypoint 2D coordinates: x, y, theta
    wp0: [1.32, -0.672, 0.0]
    wp1: [0.753, 0.555, 0.0]
    wp2: [0.626, 2.67, 0.0]
    wp3: [0.678, 4.53, 0.0]
